### ISSUE TITLE
Reject clients with wrong chain id

### ISSUE THREAD

**Issue by j4tner** [soundac/SounDAC-Source#13]
_From @pmconrad on January 16, 2018 12:22_

Followup to #56 - after we can be sure that all current nodes will publish their chain id in the client hello message, we can start rejecting clients with the wrong chain id.
https://github.com/steemit/steem/blob/07ccb8b408ff5b839f5ab2e8d2a128f1fd2edf2f/libraries/net/node.cpp#L1997

_Copied from original issue: themuseblockchain/Muse-Source#57_

**Comment by pmconrad** [comment]
Merged
